address: "http://localhost:8080"
postgres:
  dsn: "postgresql://postgres:password@postgres:5432/auth"
signer:
crypto:
  signer:
    local: true
    generate: true
  encrypter:
    local: true
providers:
  mock-provider:
    internalHost: "http://mock-provider:8080"
    externalHost: "http://localhost:8081"
    clientID: "client-id"
    clientSecret: "client-secret"
    scopes:
      - openid
      - test
