// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Code struct {
	ID     int32
	Code   string
	Userid int32
}

type User struct {
	ID int32
}

type Usertoken struct {
	Provider         string
	Provideridentity string
	Userid           int32
	Token            pgtype.Text
}
